---
- name: Required packages are installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - python-psycopg2
  - node-less  # Required for in-request django-compressor compression.

- name: Project user is present
  user:
    name: "{{ gunicorn_django_project_name }}"

- name: Home directory is present
  file:
    name: "/home/{{ gunicorn_django_project_name }}"
    state: directory
    owner: "{{ gunicorn_django_project_name }}"
    group: "{{ gunicorn_django_project_name }}"

- name: Gunicorn .service file is in place
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.{{ gunicorn_django_project_name }}.service
  register: servicefile

- name: Gunicorn .socket file is in place
  template:
    src: gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.{{ gunicorn_django_project_name }}.socket
  register: socketfile

- name: systemd units are reloaded
  command: systemctl --system daemon-reload
  when:
    servicefile|changed or socketfile|changed or tmpfiles|changed

- name: Gunicorn service is enabled and started
  service:
    name: gunicorn.{{ gunicorn_django_project_name }}
    state: started
    enabled: true
